<a href="https://colab.research.google.com/github/elifnuryaygin03/elifnuryaygin/blob/main/Copy_of_AI_Week6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Week 6

**TASK1**

Write a NumPy program to create an array of all the even integers from 30 to 70 and then print the results

In [ ]:
import numpy as np
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

**TASK 2**

Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [ ]:
np.random.normal(0,1,15)

array([-0.28859991, -1.98170054, -0.84620955, -0.92215096, -1.01007668,
        0.98040847,  0.20106487,  0.68237861,  0.44279148,  0.65505606,
       -0.64333502, -0.38446341, -1.43944927,  0.51039903,  0.71189285])

**TASK 3**

Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [ ]:
np.arange(10,22).reshape((3,4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

**TASK 4**

Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [ ]:
x=np.diag([1,2,3,4,5])

**TASK 5**

Write a NumPy program to add elements in a matrix. If an element in the matrix is 0, we will not add the element below this element

array([[ 1,  2,  3],
       [ 4,  5, 56],
       [ 6,  6,  4],
       [ 2,  3,  4]])

**TASK 6**

Write a NumPy program to sort a given array by row and column in ascending order

In [ ]:
np.sort(x,axis=0)[::-1]

array([[1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**TASK 7**

Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns.

**TASK 8**

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

**TASK 9**

You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.

**TASK 10**

Arithmetic :

https://www.hackerrank.com/challenges/np-array-mathematics/problem?isFullScreen=true


**TASK 11**

Sum and Prod

https://www.hackerrank.com/challenges/np-sum-and-prod/problem?isFullScreen=true

**TASK 12**

dot and cross :

https://www.hackerrank.com/challenges/np-dot-and-cross/problem?isFullScreen=true

**TASK 13**

min max:

https://www.hackerrank.com/challenges/np-min-and-max/problem?isFullScreen=true